#!/usr/bin/env python3
"""
Config management for Codex Proxy.

Settings: ~/.codexproxy/settings.json
API key:  ~/.codexproxy/.api_key
Codex:    ~/.codex/config.toml (auto-generated)
"""

import json
import os
import shutil
from datetime import datetime
from pathlib import Path

CONFIG_DIR = Path.home() / ".codexproxy"
SETTINGS_FILE = CONFIG_DIR / "settings.json"
API_KEY_FILE = CONFIG_DIR / ".api_key"
CODEX_CONFIG = Path.home() / ".codex" / "config.toml"

DEFAULT_SETTINGS = {
    "preset": "z.ai",
    "upstream": "https://api.z.ai/api/anthropic",
    "port": 9090,
    "host": "127.0.0.1",
    "api_type": "anthropic",
    "model_map": {
        "gpt-5.4": "claude-sonnet-4-20250514",
        "gpt-5.4-mini": "glm-5.1",
    },
}


def ensure_config_dir():
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)


def load_settings() -> dict:
    """Load settings from disk, return defaults if not found."""
    ensure_config_dir()
    try:
        with open(SETTINGS_FILE, "r", encoding="utf-8") as f:
            settings = json.load(f)
        # Merge with defaults for missing keys
        merged = {**DEFAULT_SETTINGS, **settings}
        return merged
    except (FileNotFoundError, json.JSONDecodeError):
        return DEFAULT_SETTINGS.copy()


def save_settings(settings: dict):
    """Persist settings to disk."""
    ensure_config_dir()
    with open(SETTINGS_FILE, "w", encoding="utf-8") as f:
        json.dump(settings, f, indent=2, ensure_ascii=False)


def load_api_key() -> str:
    """Load API key from disk."""
    try:
        return API_KEY_FILE.read_text(encoding="utf-8").strip()
    except FileNotFoundError:
        return ""


def save_api_key(key: str):
    """Save API key to disk."""
    ensure_config_dir()
    API_KEY_FILE.write_text(key, encoding="utf-8")
    # Restrict permissions
    os.chmod(API_KEY_FILE, 0o600)


def generate_codex_config(port: int = 9090, provider_name: str = "codex-proxy") -> str:
    """Generate ~/.codex/config.toml content."""
    return f"""# Auto-generated by Codex Proxy — {datetime.now().isoformat()}
model = "gpt-5.4"
model_provider = "{provider_name}"
sandbox_mode = "danger-full-access"

[model_providers.{provider_name}]
name = "Codex Proxy"
base_url = "http://localhost:{port}/v1"
env_key = "CODEX_PROXY_API_KEY"
wire_api = "responses"
"""


def install_codex_config(port: int = 9090, provider_name: str = "codex-proxy") -> bool:
    """Install config.toml for Codex. Backup existing if found."""
    codex_dir = CODEX_CONFIG.parent
    codex_dir.mkdir(parents=True, exist_ok=True)

    # Backup existing config
    if CODEX_CONFIG.exists():
        backup = CODEX_CONFIG.with_suffix(f".toml.bak-{datetime.now().strftime('%Y%m%d%H%M%S')}")
        shutil.copy2(CODEX_CONFIG, backup)

    content = generate_codex_config(port, provider_name)
    CODEX_CONFIG.write_text(content, encoding="utf-8")
    return True


def get_codex_config_path() -> str:
    return str(CODEX_CONFIG)
